### ISSUE TITLE
Web pages for Conditions/Triggers mssing

### ISSUE THREAD

**Issue by yuchaoran2011** [surveyjs/site#2]
When I went to this [page](https://surveyjs.io/Examples/Library/) and from the menu on the left clicked "Conditions and Triggers" --> "Complete Trigger", I got a page that said:
"Error. An error occurred while processing your request."
The same thing happened for "SetValue Trigger" and "Visible Trigger".

These two links used to work I remember. Please fix them. Thank you!

**Comment by yuchaoran2011** [comment]
@dmitrykurmanov @andrewtelnov @tsv2013

**Comment by andrewtelnov** [comment]
@yuchaoran2011 I have fixed it,

Thank you,
Andrew

**Comment by yuchaoran2011** [comment]
Thank you @andrewtelnov
