### ISSUE TITLE
The site is currently broken

### ISSUE THREAD

**Issue by AndOne1974** [surveyjs/site#3]
check the example pages, they have js errors

ReferenceError: survey is not defined

and some more ;)

**Comment by AndOne1974** [comment]
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung.  ace.min.js:1:17944
TypeError: _this.sheet.addRule is not a function[Weitere Informationen]  stylesmanager.ts:42:62
TypeError: __WEBPACK_IMPORTED_MODULE_3_survey_knockout__ is undefined[Weitere Informationen]  surveyjsObjects.ts:49:1
ReferenceError: SurveyEditor is not defined[Weitere Informationen]  Editor:159:17
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.

**Comment by AndOne1974** [comment]
already fixed, thx!

**Comment by madfactory1** [comment]
How did you solve that issue?... I have the same problem while creating a survey from my node.js application.
Thanks!
